# Generated by Django 5.2.1 on 2025-05-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_favourite_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='quantity',
        ),
    ]
