# Generated by Django 5.2.1 on 2025-06-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Loading'), ('confirmed', 'confirmed'), ('shipped', 'sent'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
